// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJvN8sWeIdDO5rNtYgLTkpaBVshoAPo2k',
    appId: '1:339399210213:web:7aa860db2b3d57f3f6900c',
    messagingSenderId: '339399210213',
    projectId: 'gasto-certo-app',
    authDomain: 'gasto-certo-app.firebaseapp.com',
    storageBucket: 'gasto-certo-app.appspot.com',
    measurementId: 'G-BXJ2NB7VWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YiOUKmbegSood3jJfhSKAMUQz4AjtPo',
    appId: '1:339399210213:android:eccdd84058a90261f6900c',
    messagingSenderId: '339399210213',
    projectId: 'gasto-certo-app',
    storageBucket: 'gasto-certo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_C55a0w6cVs4Pe-FqIJLJO3EVqT-qpGo',
    appId: '1:339399210213:ios:cf52a4f77fd79ab5f6900c',
    messagingSenderId: '339399210213',
    projectId: 'gasto-certo-app',
    storageBucket: 'gasto-certo-app.appspot.com',
    iosBundleId: 'br.com.gastocerto.gastoCerto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_C55a0w6cVs4Pe-FqIJLJO3EVqT-qpGo',
    appId: '1:339399210213:ios:bc2ea81dbfbf20e1f6900c',
    messagingSenderId: '339399210213',
    projectId: 'gasto-certo-app',
    storageBucket: 'gasto-certo-app.appspot.com',
    iosBundleId: 'br.com.gastocerto.gastoCerto.RunnerTests',
  );
}
